name: Rspec and Capybara
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Install OS dependencies
        run: sudo apt-get install libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup the postgres database
        run: bundle exec rails db:setup

      - name: Run the test suite
        run: bundle exec rspec