name: Rspec and Capybara
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code from repo
        uses: actions/checkout@v3
      - name: Install OS dependencies
        run: sudo apt-get install libpq-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0.1'
      - name: Bundle install
        run: bundle install
      - name: Setup the postgres database
        run: bundle exec rails db:setup
      - name: Run the test suite
        run: bundle exec rspec